urls.py
from django.conf.urls import patterns, url

from listings import views

urlpatterns = patterns('',
	url(r'^$', views.index),
	url(r'^status/$', views.status, name='status'),
	url(r'^login/$', views.login_user, name='login_user'),
	url(r'^logout/$', views.logout_user, name='logout_user'),
	url(r'^all/$', views.AllListings.as_view(), name='all'),
	url(r'^deleted/$', views.DeletedListings.as_view(), name='deleted'),
	url(r'^ready/$', views.ReadyListings.as_view(), name='ready'),
	url(r'^worklist/$', views.Worklist.as_view(), name='worklist'),
	url(r'listing/(?P<pk>\d+)/$', views.ListingUpdate.as_view(), name='listing_update'),
	url(r'^scrape/$', views.scrape, name='scrape'),
	url(r'^scrapenow/$', views.scrapenow, name='scrapenow'),
	url(r'^csv/$', views.csvview, name='csvview'),
	url(r'^excel/$', views.excelview, name='excelview'),
	url(r'^discover/$', views.discovernow, name='discovernow'),
	url(r'^discover/deep/$', views.discovernowdeep, name='discovernowdeep'),
	url(r'^retrieve/(?P<modifier>\w*)/(?P<offset>\d*)$', views.retrievenow, name='retrievenow'),
)



#	url(r'^(?P<listingID>\d+)/$', views.ListingUpdate.as_view(), name='listing_update'),
#	url(r'^edit/(?P<listingID>\d+)/$', views.detail, name='detail'),

models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone

class BadListing(models.Model):
	listingID = models.BigIntegerField(primary_key=True, unique=True, editable=False)

class FreshListing(models.Model):
	listingID = models.BigIntegerField(primary_key=True, unique=True, editable=False)
	url = models.CharField(max_length=254, blank=True, default='')
	trouble = models.BooleanField(default=False)
	dateRecordUpdated = models.DateTimeField(auto_now=True)
	claimed = models.DateTimeField(blank=True, null=True)
	
class Listing(models.Model):
	# Core data about listing
	listingID = models.BigIntegerField(primary_key=True, unique=True, editable=False)
	listingBody = models.TextField()	
	listingType = models.CharField(max_length = 3)
	
	# Data scraped from listing
	title = models.CharField(max_length = 255, blank=True, default='')
	attributeGroup = models.TextField(default='')
	price = models.IntegerField(null=True, blank=True)
	bedrooms = models.SmallIntegerField(null=True)
	address = models.CharField(max_length=254, blank=True, default='')
	phone = models.CharField(max_length = 30, blank=True, default='')
	area = models.SmallIntegerField(null=True, blank=True)
	mapUrl = models.URLField(blank=True, default='')
	dateListingPosted = models.DateTimeField()
	dateListingUpdated = models.DateTimeField(null=True, blank=True)
	
	# Computed or added later
	neighborhood = models.CharField(max_length = 100, blank=True, default='')
	city = models.CharField(max_length = 100, blank=True, default='')
	county = models.CharField(max_length = 30, blank=True, default='')
	zip = models.CharField(max_length = 10, blank=True, default='')
	region = models.CharField(max_length = 100, blank=True, default='')
	available = models.CharField(max_length = 100, blank=True, default='')
	sublet = models.BooleanField(default=False)
	shared = models.BooleanField(default=False)

	# Utilities
	gas = models.BooleanField(default=False)
	heat = models.BooleanField(default=False)
	electricity = models.BooleanField(default=False)
	internet = models.BooleanField(default=False)
	cable = models.BooleanField(default=False)
	lawn_care = models.BooleanField(default=False)
	snow_removal = models.BooleanField(default=False)
	trash = models.BooleanField(default=False)
	water = models.BooleanField(default=False)

	# Amenities
	laundry = models.CharField(max_length = 99, blank=True, default='')
	parking = models.CharField(max_length = 99, blank=True, default='')    
	#parkingPrice = models.CharField(max_length = 99, null=True, blank=True, default='')    
	dogsAllowed = models.NullBooleanField()
	catsAllowed = models.NullBooleanField()
	#petPrice = models.CharField(max_length = 99, null=True, blank=True, default='')    
	noSmoking = models.NullBooleanField()
		
	# Metadata about this record
	deleted = models.BooleanField(default=False)
	dateListingScraped = models.DateTimeField()
	dateRecordUpdated = models.DateTimeField(auto_now=True)
	updatedBy = models.ForeignKey(User, null=True)
		
	class Meta:
		ordering = ["-listingID"]
	
	def get_absolute_url(self):
		return reverse('listing_update', kwargs={'pk': self.pk})
		
	# Combined output of several attributes for the description column
	def descriptionField(self):			
		# Make amenities from parking, laundry, pets, and smoking 
		amenities = []
		if self.parking:
			amenities.append(self.parking)
		if self.laundry:
			amenities.append(self.laundry)
		if self.dogsAllowed and self.catsAllowed:
			amenities.append('cats & dogs allowed')
		elif self.dogsAllowed: 
			amenities.append('dogs allowed')
		elif self.catsAllowed:
			amenities.append('cats allowed')
		if self.noSmoking:
			amenities.append('no smoking')

		utilities = []
		if self.electricity:
			utilities.append('electricity')
		if self.heat:
			utilities.append('heat')
		if self.water:
			utilities.append('water')
			
		description = 'Utilities included: '
		if self.electricity == None and self.heat == None and self.water == None:
			description = description + 'unknown'
		elif len(utilities)==0:
			description = description + 'none'
		else:
			description = description + ', '.join(utilities)
			
		if len(amenities)>0:
			description = description + "; Amenities include: " + '; '.join(amenities)
			#description = description.replace(',', ' ')
			
		return description
			
	# Combined output for the bedrooms column with the # of rooms plus the type of rental
	def bedroomsField(self):
		if self.shared:
			return 'Shared(0)'
		if self.sublet:
			return 'Sublet(' + str(self.bedrooms) + ')'
		return self.bedrooms

	def addressWithNeighborhood(self):
		if self.neighborhood == '':
			return self.address
		if self.address == '':
			return self.neighborhood
		return '%s (%s)' % (self.address, self.neighborhood)
		
	def url(self):
		baseUrl = 'madison.craigslist.org'
		return 'http://%s/%s/%s.html' % (baseUrl, self.listingType, self.listingID)
		
	def mapQueryString(self):
		q=''
		try:
			q = self.mapUrl.split('?q=')[1]
		except:
			pass
		return q

	def representation(self):
		return ('Listing(\n     id=%s\n     deleted=%s\n     price=%s\n     listingType=%s\n     address=%s\n     phone=%s\n     bedrooms=%s\n     laundry=%s\n     parking=%s\n     dogsAllowed=%s\n     catsAllowed=%s\n     noSmoking=%s\n     area=%s\n     zip=%s\n     county=%s\n     neighborhood=%s\n     mapUrl=%s\n     )' % (repr(self.listingID), repr(self.deleted), repr(self.price), repr(self.listingType), repr(self.address), repr(self.phone), repr(self.bedrooms), repr(self.laundry), repr(self.parking), repr(self.dogsAllowed), repr(self.catsAllowed), repr(self.noSmoking), repr(self.area), repr(self.zip), repr(self.county), repr(self.neighborhood), repr(self.mapUrl)))
		
	def __str__(self):
		return(self.representation())
		
	def __repr__(self):
		return(self.representation())

templates/listings/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="michael donnelly">
    <link rel="shortcut icon" href="../../assets/ico/favicon.ico">

    <title>TRC Housing Vacancy List</title>

    <!-- Bootstrap core CSS -->
    <link href="http://robothijinks.com/~donnelly/bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
	<link href="http://robothijinks.com/~donnelly/bower_components/bootstrap/less/jumbotron.less" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'listings/starter-template.css' %}" rel="stylesheet">

  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">{% block title %}Housing Vacancy List{% endblock %}</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            {% block overrideNavlinks %}
            <li><a href="{% url 'listings.views.index' %}">Home</a></li>
            {% endblock %}
            {% block appendNavlinks %} {% endblock %}
          </ul>
 		    {% if user.is_authenticated %}
			<form class="navbar-form navbar-right" role="form" name='logout' action='{% url 'listings.views.logout_user' %}'>
				<button type="submit" class="btn">Sign  out {{ user.username }}</button>
			</form>
			{% else %}
          	<form class="navbar-form navbar-right" role="form" name='login' action='{% url 'listings.views.login_user' %}' method='post'>
          		{% csrf_token %}
				<div class="form-group">
				  <input type="text" name='username' placeholder="Username" class="form-control">
				</div>
				<div class="form-group">
				  <input type="password" name='password' placeholder="Password" class="form-control">
				</div>
				<button type="submit" class="btn">Sign in</button>
          	</form>
            {% endif %}
          
          
          	
          
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container">
		<div class="starter-template">
			{% block content %}{% endblock %}
		</div>
    </div><!-- /.container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="http://robothijinks.com/~donnelly/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
  </body>
</html>

templates/listings/index.html
{% extends "listings/base.html" %}

<link href="http://robothijinks.com/~donnelly/bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
<link href="http://robothijinks.com/~donnelly/bower_components/bootstrap/less/jumbotron.less" rel="stylesheet">

{% block content %}
<div class='row'>
	<div class='col-md-4'> 
		<h3>View & Edit Listings</h3>
		<ul>
			<li><a href='worklist'>Current worklist</a></li>
			<li><a href='ready'>Ready to post</a></li>
			<li><a href='deleted'>Deleted</a></li>
			<li><a href='all'>All listings</a></li>
		</ul>
	</div>
	
	<div class='col-md-4'> 
		<h3>Manage Vacancy List</h3>
		<ul>
			<li><a href='discover'>Get the index pages and extract the listing IDs and URLs</a></li>
			<li><a href='retrieve'>Scrape each of the new listings that hasn't been scraped before</a></li>
			<!--<li><a href='scrapenow'>Download listings from craigslist (in foreground)</a></li>
			<li>Download listings from craigslist (in background)</li>-->
			<li><a href='excel'>Publish Excel spreadsheet of current listings</a></li>
			<!--<li><a href='csv'>Publish as comma separated values</a></li>-->
		</ul>
		
	</div>
	
	<div class='col-md-4'> 
		<h3>Administration</h3>
		<ul>
		</ul>
	</div>
	
</div>
{% endblock %}

templates/listings/listing_form.html
{% extends "listings/base.html" %}
{% load listing_extras %}

{% block title %} 
{% listing_title listing %}
{% endblock %}

{% block appendNavlinks %} 
<li><a href="/hvl/worklist">Return to Worklist</a></li>
{% endblock %}


{% block content %}

<!-- Sample listing -->
<div class='well well-sm'>
	<table class='table'>
		<tr>
			<td>#BR</td>
			<td>Price</td>
			<td>Contact</td>
			<td>Description</td>
			<td>Available</td>
			<td>Address</td>
			<td>Region</td>
		</tr>
		<tr>
			<td>{{listing.bedroomsField}}</td>
			<td>${{listing.price}}</td>
			<td>{{listing.phone}}</td>
			<td>{{listing.descriptionField}}</td>
			<td>{{listing.available}}</td>
			<td>{{listing.address}}</td>
			<td>{{listing.region}}</td>
		</tr>
	</table>		
</div>

<form role='form form-horizontal' method="post">
	{% csrf_token %}
	{{ form.non_field_errors }}
	
	<!-- Basics, Location -->
	<div class='row'>
		<!-- Basics -->
		<div class='col-md-4'> 
			<h3>Basics</h3>
			<div class='form-group'>
				<div class="fieldWrapper">
					{{ form.price.errors }}
					<label for="id_price" class='control-label col-sm-2'>Price:</label>
					<div class='col-sm-4'>
						<input type='number' class='form-control' id='id_price' name='price' value={{listing.price}}>
					</div>
				</div>
				<div class="fieldWrapper">
					{{ form.bedrooms.errors }}
					<label for="id_bedrooms" class='control-label col-sm-3'>Bedrooms:</label>
					<div class='col-sm-3'>
						<input type='number' class='form-control' id='id_bedrooms' name='bedrooms' value={{listing.bedrooms}}>
					</div>
				</div>
			</div>
			<div class='form-group'>
				<div class="col-sm-6">
					<div class="fieldWrapper checkbox">
						<label>
							<input type="checkbox" id='id_sublet' name='sublet' {% if listing.sublet %}checked='on'{% endif %}/> Sublet
						</label>
					</div>
				</div>
				<div class="col-sm-6">
					<div class="fieldWrapper checkbox">
						<label>
								<input type="checkbox" id='id_shared' name='shared' {% if listing.shared %}checked='on'{% endif %}/> Shared
							</label>
					</div>
				</div>
			</div>
			<div class='form-group'>
				<label for='phone' class='control-label col-sm-3'>Contact</label>
				<div class='col-sm-9 fieldWrapper'>
					{{ form.phone.errors }}
					<input type='phone' class='form-control' id='id_phone' name='phone' value='{{listing.phone}}'>
				</div>
			</div>		
			<div class='form-group'>
				<label for='available' class='control-label col-sm-3'>Available</label>
				<div class='col-sm-9 fieldWrapper'>
					{{ form.available.errors }}
					<input type='text' class='form-control' id='id_available' name='available' value='{{listing.available}}'>
				</div>
			</div>			
			<div>
				<a class='btn btn-primary' href='{{listing.url}}'>Original Post</a>
			</div>
		</div>

		<!-- Location -->
		<div class='col-md-4'>
			<h3>Location</h3>
			<div class='form-group'>
				<label for='id_address' class='control-label col-sm-3'>Address</label>
				<div class='col-sm-9'>
					<input type='text' class='form-control' id='id_address' name='address' value='{{listing.address}}'>
				</div>
			</div>
			<div class='form-group'>
				<label for='id_region' class='control-label col-sm-3'>Region</label>
				<div class='col-sm-9'>
					<input type='text' class='form-control' id='id_region' name='region' value='{{listing.region}}'>
				</div>
			</div>
			{% address_display listing %}
		</div>	

		<!-- Map -->
		<div class='col-md-4'>
			{%if listing.mapQueryString %}
			<iframe
				width="400"
				height="300"
				frameborder="0" style="border:0"
				src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCQJ16My4P-aIymwWODzBDdyYOrcZnK9t8
				&q={{listing.mapQueryString}}&zoom=15">  # zoom=
			</iframe>
			{% else %}
			No map available
			{% endif %}
		</div>
	
	</div>

	<!-- Listing -->
	<div class='row'>
		<div class='col-md-12'>
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						<a href='{{listing.url}}' target="_blank">
							{% firstof listing.title listing.listingID %}
						</a>
					</h3>
				
				</div>
				<div class="panel-body">
					<div class='row'>
						<div class='col-md-11'>
							{{listing.listingBody}}
						</div>
						<div class='col-md-1'>
							{{listing.attributeGroup|safe}}
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--<a href="{{listing.url}}" class="btn btn-primary active" role="button">View listing</a>-->
	</div>

	<!-- Utilities, Amenities, Buttons -->
	<div class='row'>

		<!-- Utilities -->
		<div class='col-md-3'> 
			<h3>Utilities Include</h3>			
		
			<div class='form-group'>
				{% checkbox gas listing.gas %}
				{% checkbox heat listing.heat %}
				{% checkbox electricity listing.electricity %}
				{% checkbox internet listing.internet %}
				{% checkbox cable listing.cable %}
				{% checkbox lawn_care listing.lawn_care %}
				{% checkbox snow_removal listing.snow_removal %}
				{% checkbox trash listing.trash %}
				{% checkbox water listing.water %}

			</div>
		
		
		</div>

		<!-- Amenities -->
		<div class='col-md-4'> 
			<h3>Amenities</h3>
			<div class='form-group'>
				<label for='id_parking' class='control-label col-sm-3'>Parking</label>
				<div class='col-sm-9'>
					<input type='text' class='form-control' id='id_parking' name="parking" value='{{listing.parking}}'>
				</div>
			</div>
			<div class='form-group'>
				<label for='id_laundry' class='control-label col-sm-3'>Laundry</label>
				<div class='col-sm-9'>
					<input type='text' class='form-control' id='id_laundry' name='laundry' value='{{listing.laundry}}'>
				</div>
			</div>
	
			<div class='form-group'>
				<h4>Pets</h4>
				{% checkbox catsAllowed listing.catsAllowed %}
				{% checkbox dogsAllowed listing.dogsAllowed %}
			</div>
			
			<div class='form-group'>
				<h4>Other</h4>
				{% checkbox noSmoking listing.noSmoking %}
			</div>
			
			
	
	
	
		</div>
	
		<!-- Buttons -->
		<div class='col-md-4'>
			<p>
				<button type="submit" value="save" name="saveStay" class="btn btn-lg btn-block btn-primary">Save</button>
			</p>
			<p>
				<button type="submit" value="save" name="saveClose" class="btn btn-lg btn-block btn-primary">Save & Close</button>
			</p>
			<p>
				<button type="submit" value="delete" name="deleteRecord" class="btn btn-lg btn-block btn-danger">Delete</button>
			</p>
			<p>
				<button type="submit" value="rescrape" name="rescrape" class="btn btn-lg btn-block btn-caution">Download Again</button>
			</p>
		</div>
	
	</div>
</form>

<!-- Timestamps -->
<div class="container"><small><i>
	<ul class='list-inline'>
		<li>Posted: {{listing.dateListingPosted}}</li>
		<li>Listing Updated: {{listing.dateListingUpdated}}</li>
		<li>Scraped: {{listing.dateListingScraped}}</li>
		{% if listing.updatedBy %}
		<li>Record Updated: {{listing.dateRecordUpdated}} by {{listing.updatedBy}}</li>
		{% endif %}
	</ul>
</i></small></div>
{% endblock %}

templates/listings/listing_list.html
{% extends "listings/base.html" %}

{% block content %}
<table class='table'>
	<tr>
		<th>ID</th>
		<th>#BR</th>
		<th>Price</th>
		<th>Available</th>
		<th>Address</th>
		<th>Region</th>
		<th>Record Updated</th>
	</tr>

	{% for listing in object_list %}
	<tr>
		<td><a href="listing/{{ listing.listingID }}">{{ listing.listingID }} </a></td>
		<td>{{listing.bedroomsField}}</td>
		<td>${{listing.price}}</td>
		<td>{{listing.available}}</td>
		<td>{{listing.address}}</td>
		<td>{{listing.region}}</td>
		<td>{{listing.dateRecordUpdated}}</td>
	</tr>
	{% endfor %}
</table>		
{% endblock %}